# This file intentionally left blank
WS2812_DRIVER = vendor
SERIAL_DRIVER = vendor

TAP_DANCE_ENABLE = yes
DYNAMIC_TAPPING_TERM_ENABLE = yes

OLED_ENABLE = yes
OLED_DRIVER = SSD1306
OLED_TRANSPORT = i2c

ENCODER_MAP_ENABLE = yes
